### PR TITLE
update to go 1.18 and dependencies

### PR DESCRIPTION
**Pull request by dskart**
updates to go 1.18 and fixes all dependencies. (also cleans up `simplifycompositelit` stuff)

### CODE REVIEW

**Comment by dskart** [comment]
currently foundation db fails with this:

```bash
ok      github.com/ccbrown/keyvaluestore        (cached)
# github.com/apple/foundationdb/bindings/go/src/fdb
../../../go/pkg/mod/github.com/apple/foundationdb/bindings/go@v0.0.0-20220423002849-9b6644778399/src/fdb/database.go:26:11: fatal error: 'foundationdb/fdb_c.h' file not found
 #include <foundationdb/fdb_c.h>
          ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
ok      github.com/ccbrown/keyvaluestore/dynamodbstore  (cached)
FAIL    github.com/ccbrown/keyvaluestore/foundationdbstore [build failed]
ok      github.com/ccbrown/keyvaluestore/keyvaluestorecache     (cached)
ok      github.com/ccbrown/keyvaluestore/keyvaluestoreinvalidator       (cached)
?       github.com/ccbrown/keyvaluestore/keyvaluestoretest      [no test files]
ok      github.com/ccbrown/keyvaluestore/memorystore    (cached)
ok      github.com/ccbrown/keyvaluestore/redisstore     (cached)
FAIL
```

**Comment by dskart** [comment]
[https://github.com/dskart/keyvaluestore/pull/4](https://github.com/dskart/keyvaluestore/pull/4) for github actions

**Comment by ccbrown** [comment]
Could you update the Go version in Dockerfile-dev too? That looks like the reason CI fails.

**Review by ccbrown — CHANGES_REQUESTED** [review]
See comment.

**Comment by dskart** [comment]
should be fixed!

**Review by ccbrown — APPROVED** [review]
Awesome. Generics for the win.

**Pull request merged**
